Messages:
  noPermission: "&b[&cTalismanes&b] &eNo tienes permiso para hacer esto."
  notEnoughArgs: "&b[&cTalismanes&b] &eNo has especificado suficientes argumentos."
  reload: "&b[&cTalismanes&b] &eEl plugin se ha recargado con éxito."
  talismanGiven: "&b[&cTalismanes&b] &eHas conseguido el talismán %talisman%&e."
  talismanGiveArguments: "&b[&cTalismanes&b] &eEl uso es /voodootalismans give <Talismán> [Jugador]."
  talismanRemoved: "&b[&cTalismanes&b] &eHas perdido el talismán %talisman%&e."
  talismanRemoveArguments: "&b[&cTalismanes&b] &eEl uso es /voodootalismans remove <Talismán> [Jugador]."
  noTalismansFound: "&b[&cTalismanes&b] &eNo tienes ningún talismán."
  pageNotFound: "&b[&cTalismanes&b] &eNo se ha encontrado la página a la que quieres acceder."
  menuNextPage: "Ir a página %next_page%"
  menuPreviousPage: "Ir a página %previous_page%"
  cannotActivateMore: "&b[&cTalismanes&b] &eNo puedes activar más de %amount% talismanes."
  playerAlreadyHasTalismans: "&b[&cTalismanes&b] &eEse jugador ya tiene ese talismán."
  playerDoesNotHaveTalisman: "&b[&cTalismanes&b] &eEse jugador no tiene ese talismán."
  talismanLevelUp: "&b[&cTalismanes&b] &eEl talismán %name% &eha subido al nivel %level%."
  talismanCannotLevelUp: "&b[&cTalismanes&b] &eEl talismán %name% &eya ha alcanzado su nivel máximo."
  help:
    - "&d&m -===- &b[&cTalismanes&b] &d&m-===-"
    - "&b/voodootalismans &eMuestra esta página."
    - "&b/voodootalismans give <Talismán> [Jugador] &eDa un talismán a un jugador."
    - "&b/voodootalismans remove <Talismán> [Jugador] &eElimina un talismán a un jugador."
    - "&b/voodootalismans list &eMuestra todos los talismanes disponibles."
    - "&b/voodootalismans reload &eRecarga la configuración del plugin."
    - "&b"
    - "&eLeyenda: &b<> &eObligatorio  &b[] &eOpcional"
    - "&d&m -===- &b[&cTalismanes&b] &d&m-===-"

Menu:
  title: "&aTalismanes (%active%/%total%)"
  borderMaterial: GRAY_STAINED_GLASS_PANE
  level: "&7Nivel &d%level%"
  maxLevel: "&7Nivel: &d%level% &a&lMÁXIMO"
  effects: "&7Efectos:"
  active: "&aActivo"
  unactive: "&cInactivo"
  select: "&eHaz clic para activar"
  deselect: "&eHaz clic para desactivar"
  missingTalismansSlot: 4
  missingTalismansMaxTalismansPerPage: 15
  missingTalismansItem:
    material: FLOWER_BANNER_PATTERN
    name: "&b&lTalismanes faltantes &e(&a%current%&e/&c%max%&e)"
    lore:
      - ''
      - '&a&l➤ TALISMANES &a(&d%length%&a):'
    nextPage: "&7Clic izquierdo para pasar a la página siguiente."
    previousPage: "&7Clic derecho para regresar a la página anterior."
    glow: true

Talismans:
  voodooDoll:
    name: "&5Muñeco vudú"
    material: TOTEM_OF_UNDYING
    maxLevel: 10
    lore:
      - ""
      - "&7Muñeco vudú usado para"
      - "&7tortutar a tus víctimas."
    glow: true
    effects:
      addModifierScaleArmor:
        attribute: armor
        value: 0.1
        lore: "  &8» &a+%value%&7 de armadura"
      addModifierValueArmorToughness:
        attribute: armor_toughness
        value: 2
        lore: "  &8» &7Multiplicador de &ax%value%&7 de armor toughness"
      addItemChanceFishing:
        type: fishing
        value: 5
        lore: "  &8» &a+%value%%&7 de probabilidad de objeto al pescar"
      addItemChanceWoodcutting:
        type: woodcutting
        value: 5
        lore: "  &8» &a+%value%%&7 de probabilidad de objeto al talar"
      addCreatureChanceFishing:
        type: fishing
        value: 3
        lore: "  &8» &a+%value%%&7 de probabilidad de criatura al pescar"
      addCreatureChanceWoodcutting:
        type: woodcutting
        value: 3
        lore: "  &8» &a+%value%%&7 de probabilidad de criatura al talar"
      addGemChance:
        value: 2
        lore: "  &8» &a+%value%%&7 de probabilidad de gema"
      addFoodChance:
        value: 2
        lore: "  &8» &a+%value%%&7 de probabilidad de comida"
      addDoubleChanceFishing:
        type: fishing
        value: 1
        lore: "  &8» &a+%value%%&7 de probabilidad de doble recompensa al pescar"
      addDoubleChanceWoodcutting:
        type: woodcutting
        value: 1
        lore: "  &8» &a+%value%%&7 de probabilidad de doble recompensa al talar"
      addDoubleChanceMining:
        type: mining
        value: 1
        lore: "  &8» &a+%value%%&7 de probabilidad de doble recompensa al minar gemas"
      addDoubleChanceFood:
        type: food
        value: 1
        lore: "  &8» &a+%value%%&7 de probabilidad de doble recompensa al conseguir comidas"
      addBoostRarityChanceFishing:
        type: fishing
        rarity: legendary
        value: 1
        lore: "  &8» &a+%value%%&7 de probabilidad de legendario al pescar"
      addBoostRarityChanceWoodcutting:
        type: woodcutting
        rarity: legendary
        value: 1
        lore: "  &8» &a+%value%%&7 de probabilidad de legendario al talar"